import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPORTS_DIR = path.join(__dirname, '../../reports');
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

export function generateAuditPdfReport(claim, analysis) {
  return new Promise((resolve, reject) => {
    try {
      const fileName = `Audit_Report_${claim.claim_number}.pdf`;
      const filePath = path.join(REPORTS_DIR, fileName);

      const doc = new PDFDocument({ margin: 40 });
      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // Header Banner
      doc
        .rect(0, 0, doc.page.width, 70)
        .fill('#0f172a');

      doc
        .fillColor('#ffffff')
        .fontSize(20)
        .font('Helvetica-Bold')
        .text('MEDIFRAUD GUARD', 40, 20);

      doc
        .fontSize(10)
        .font('Helvetica')
        .text('Medical Reimbursement Fraud Detection & Compliance Audit Report', 40, 45);

      // Report Info Meta Box
      doc.moveDown(3);
      doc
        .fillColor('#1e293b')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(`Claim Summary: ${claim.claim_number}`, 40, 95);

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#475569')
        .text(`Report Generated: ${new Date().toLocaleString()}`, 40, 118);

      // Risk Badge Box
      const riskColor = claim.risk_level === 'HIGH' ? '#dc2626' : claim.risk_level === 'MEDIUM' ? '#d97706' : '#16a34a';
      doc
        .rect(380, 90, 180, 45)
        .fill(riskColor);

      doc
        .fillColor('#ffffff')
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(`RISK SCORE: ${claim.risk_score}%`, 390, 100);

      doc
        .fontSize(10)
        .text(`LEVEL: ${claim.risk_level}`, 390, 118);

      // Claim Details Table
      doc.moveDown(3);
      doc
        .fillColor('#0f172a')
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Claim Details');

      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, 165).lineTo(560, 165).stroke();

      const details = [
        ['Patient Name:', claim.patient_name || 'N/A', 'Invoice Number:', claim.invoice_number || 'N/A'],
        ['Hospital/Provider:', claim.provider_name || 'N/A', 'Invoice Date:', claim.invoice_date || 'N/A'],
        ['Attending Doctor:', claim.doctor_name || 'N/A', 'Billed Amount:', `Rs. ${(claim.total_amount || 0).toLocaleString('en-IN')}`],
        ['Registration No:', claim.registration_number || 'N/A', 'Review Status:', claim.reviewer_decision || 'UNDER_REVIEW']
      ];

      let y = 180;
      doc.font('Helvetica').fontSize(10).fillColor('#334155');
      details.forEach((row) => {
        doc.font('Helvetica-Bold').text(row[0], 40, y);
        doc.font('Helvetica').text(row[1], 150, y);
        doc.font('Helvetica-Bold').text(row[2], 330, y);
        doc.font('Helvetica').text(row[3], 440, y);
        y += 20;
      });

      // Fraud Risk Breakdown & Reasons
      y += 15;
      doc
        .fillColor('#0f172a')
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Risk Explainability Breakdown', 40, y);

      y += 18;
      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, y).lineTo(560, y).stroke();
      y += 10;

      const reasons = analysis && analysis.explainability_reasons 
        ? JSON.parse(analysis.explainability_reasons)
        : ['Standard verification complete.'];

      reasons.forEach((reason) => {
        doc
          .fillColor('#991b1b')
          .font('Helvetica-Bold')
          .fontSize(10)
          .text('• ', 40, y);
        
        doc
          .fillColor('#334155')
          .font('Helvetica')
          .text(reason, 55, y, { width: 500 });
        
        y += 22;
      });

      // Reviewer Notes & Decision Trail
      y += 15;
      doc
        .fillColor('#0f172a')
        .fontSize(12)
        .font('Helvetica-Bold')
        .text('Compliance Decision Trail', 40, y);

      y += 18;
      doc.strokeColor('#cbd5e1').lineWidth(1).moveTo(40, y).lineTo(560, y).stroke();
      y += 10;

      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .fillColor('#1e293b')
        .text('Final Decision: ', 40, y);

      doc
        .font('Helvetica')
        .text(claim.reviewer_decision, 130, y);

      y += 18;
      doc
        .font('Helvetica-Bold')
        .text('Reviewer Notes: ', 40, y);

      doc
        .font('Helvetica')
        .text(claim.reviewer_notes || 'No notes added.', 130, y, { width: 420 });

      // Footer
      doc
        .fontSize(8)
        .fillColor('#94a3b8')
        .text('Confidential - Generated by MediFraud Guard Compliance Engine', 40, 750, { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve({ fileName, filePath });
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (err) {
      reject(err);
    }
  });
}
